### ISSUE TITLE
Storing basic options separately from app config

### ISSUE THREAD

**Issue by petersohn** [home-assistant/appdaemon#67] opened 2017-06-14 14:44 UTC
What I want to do is to push the app configuration to Github along with the apps themselves, but keep the other configuration (host, password etc.) locally. Is there any way to achieve this? There should be something similar to Home Assistant's secret handling, or at least a way to store configuration in multiple files.

**Comment by acockburn** [comment] 2017-06-14 14:50
I like the idea of the secret handling - I think I will. do it that way. I'll add this in a future release when I am done with the HADashboard Beta.

**Comment by duffrecords** [comment] 2017-06-16 05:37
This is a feature I would like to see as well.  I was thinking that, for individual apps, I could store the unique name of a secret in appdaemon.cfg and then have the app use that name to look up the actual value in an untracked file but that wouldn't help with the Home Assistant API key being in the AppDaemon config.  It would be easier to manage if that logic was built into AppDaemon anyway.

**Comment by acockburn** [comment] 2017-06-16 12:55
OK, seems like I can handle both scenarios by allowing an include directive of some sort.

In v2 of AppDaemon I am moving to YAML config files so I will look at adding it to that.

**Comment by acockburn** [comment] 2017-07-09 20:21
This is on my feature list so closing the issue.

**Closed by acockburn** 2017-07-09 20:21 UTC

**Comment by duffrecords** [comment] 2017-07-15 00:56
Does this mean it's now possible to store the HA key separately?  I can't tell from the README.

**Comment by petersohn** [comment] 2017-07-15 07:19
No, it means that it will be done at some time. I think maybe it's not a good idea to close the issue, because someome else may report it again on the basis of "there is no such thing among the open issues", and they would be right.

**Comment by pho3nixf1re** [comment] 2017-10-24 21:06
Looks like that is exactly what has happened. duplicate https://github.com/home-assistant/appdaemon/issues/167 is a duplicate of this issue.

It would be great if AppDaemon would just look first in the environment variables and use those if they aren't defined in the config. These environment variables already exist due to the Docker documentation and it's a common pattern to keep secrets in env variables.

**Comment by petersohn** [comment] 2017-10-25 07:48
@pho3nixf1re It's not really a duplicate. This issue is fixed by the YAML configuration, while #167 is written for the version that already uses YAML configuration.
