### ISSUE TITLE
4.0.0b1 bug: Unexpected error in JSON conversion

### ISSUE THREAD

**Issue by bachya** [home-assistant/appdaemon#652] opened 2019-09-01 01:24 UTC
I'm seeing the following in my logs when several instances of the same automation – which toggles a switch on/off – execute at the same time:

```
2019-08-31 18:39:51.014302 INFO garage_lights_off_after_garage_close_automation: Turning off: switch.garage_lights
2019-08-31 19:00:01.409731 INFO garage_lights_on_garage_open_sundown_automation: Turning on: switch.garage_lights
2019-08-31 19:00:27.407883 INFO AppDaemon: Previous message repeated 1 times
2019-08-31 19:00:27.408084 WARNING AppDaemon: Unexpected error in JSON conversion
2019-08-31 19:00:27.429925 INFO garage_lights_on_upon_arrival_automation: Someone came home; turning on the switch
2019-08-31 19:00:27.432442 INFO bar_cart_on_upon_arrival_automation: Someone came home; turning on the switch
2019-08-31 19:00:27.436904 INFO living_room_lights_on_upon_arrival_automation: Someone came home; turning on the switch
2019-08-31 19:00:27.438616 INFO bar_cart_on_upon_arrival_automation: Turning on: switch.bar_cart
2019-08-31 19:00:27.442639 INFO living_room_lights_on_upon_arrival_automation: Turning on: group.living_room_lights
2019-08-31 19:05:27.009605 INFO AppDaemon: Previous message repeated 1 times
2019-08-31 19:05:27.010421 WARNING AppDaemon: Unexpected error in JSON conversion
2019-08-31 19:11:06.022479 INFO garage_lights_off_after_garage_close_automation: Turning off: switch.garage_lights
```

**Comment by acockburn** [comment] 2019-09-01 18:52
Lets try to get some more info - this is related to the new Admin UI.

Can you reproduce the problem with module level debug for the stream cvomnponent please?

Add this to the AD command line:

`-m _stream DEBUG`

**Comment by acockburn** [comment] 2019-09-06 18:45
Have you seen this again with the debug on?

**Comment by bachya** [comment] 2019-09-06 19:59
So strange: I actually haven't seen it reoccur. I had to revert back to AD 3.x because [this issue](https://github.com/home-assistant/appdaemon/issues/462) affects several of my apps, but once I can get 4.0.0bx back on there, I will stay on the lookout.

**Comment by acockburn** [comment] 2019-09-08 14:29
OK cool - we should get that fix in before the end of beta. I'll close this for now but please re-open if you see the issue again.

**Closed by acockburn** 2019-09-08 14:29 UTC

**Comment by electrofloat** [comment] 2019-11-10 18:07
I just run into this issue. 
It seems to be happening when I'm calling the run_daily function with a kwargs parameter like this:
`self.run_daily(self.callback, schedule.start, constrain_days=schedule.get_days_of_week(), entity_temps = schedule.entity_temps)`

if I remove the `entity_temps` parameter, the warning disappears.

**Comment by dlashua** [comment] 2019-11-11 01:20
At the moment, yes, all kwargs to callbacks have to JSON serializable.

The reason is because the kwargs are presented in an internal entity that represents the callback. This entity has to be able to survive communication via a JSON encoded websocket connection (usable for any purpose, but, primarily used in the Admin UI).

However, as you mention, this does add limits to what can be passed by kwargs. So, whether this should remain the case or not is something @acockburn will need to decide. Having the kwargs in the admin entity is very useful for metrics, debugging, health checks, etc. However, it may not outweigh the simplicity of being able to include any object in callback kwargs.

**Comment by electrofloat** [comment] 2019-11-11 08:52
I see. Maybe it could be resolved by documenting that a kwargs user class has to implement some to_json/from_json or serialize/deserialize functions, in that way the JSON can live on and the user can implement it for their custom classes.
