### ISSUE TITLE
Listen to attribute state change seems to trigger too often

### ISSUE THREAD

**Issue by CorBer** [home-assistant/appdaemon#131] opened 2017-09-04 04:45 UTC
I am using appdaemon to translate raw incoming MQTTdata into a “sensor.node_xx” variable with temperature and attributes (solar, rssi, battery, timestamp) in Home_assistant using self.set_state(…)

The code to listen to act when the "solar" attribute changes is the same as in the API docs:
`self.listen_state(self.change_light,"sensor.node_f0", attribute = "solar")`

This triggers more often than necessary also when attribute "solar" has not changed.
See
https://community.home-assistant.io/t/listen-to-attribute-state-change-seems-to-trigger-too-often/26110?u=registax

**Comment by eBoon123** [comment] 2017-09-12 22:43
I believe I am seeing something similar as well. See
https://community.home-assistant.io/t/motion-detectors-what-am-i-doing-wrong/26975

**Comment by acockburn** [comment] 2017-09-17 14:11
Closing per the above thread. This is intended behavior for components that send state updates when no state has changed. To work around it, be more explicit in the old and new states.

**Comment by CorBer** [comment] 2017-09-17 14:19
Hi,

It would be nice to make this clear in the documentation, I just use a workaround and thats fine.

regards
Cor

**Comment by acockburn** [comment] 2017-09-17 15:32
Re-opening as the explanation doesn't seem to fit the first problem report (although it does explain the second)

**Closed** 2017-12-23 21:28 UTC
