### ISSUE TITLE
KeyError: 'next_setting'

### ISSUE THREAD

**Issue by bachya** [home-assistant/appdaemon#411] opened 2018-11-03 04:38 UTC
Using AppDaemon 3.0.2, I get these unhandled exceptions when starting up:

```
2018-11-02 22:36:18.319316 WARNING AppDaemon: ------------------------------------------------------------
2018-11-02 22:36:18.319397 WARNING AppDaemon: Unexpected error running initialize() for master_bedroom_lights_on_at_sunset_automation
2018-11-02 22:36:18.319506 WARNING AppDaemon: ------------------------------------------------------------
2018-11-02 22:36:18.319820 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1581, in init_object
    init()
  File "/config/apps/switches.py", line 188, in initialize
    if self.properties.get('presence_required') else None)
  File "/usr/lib/python3.6/site-packages/appdaemon/appapi.py", line 434, in run_at_sunset
    handle = self._schedule_sun(name, "next_setting", callback, **kwargs)
  File "/usr/lib/python3.6/site-packages/appdaemon/appapi.py", line 420, in _schedule_sun
    event = self.calc_sun(type_)
  File "/usr/lib/python3.6/site-packages/appdaemon/appapi.py", line 261, in calc_sun
    return self.AD.calc_sun(type_)
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 897, in calc_sun
    return self.sun[type_].timestamp()
KeyError: 'next_setting'
```

A restart of AppDaemon without restarting HASS seems to fix things.

**Comment by acockburn** [comment] 2018-11-03 13:50
Can you post your app code please?

**Comment by bachya** [comment] 2018-11-03 15:47
You bet; let me know if you have questions.

https://github.com/bachya/smart-home/blob/777f3e117aa7844ca3392b6c0b4d0ac8ea17641a/appdaemon/settings/apps/switches.py#L172

**Comment by acockburn** [comment] 2018-11-03 17:55
It's not at all clear from your code what the heck is going on here ;) I guess you are inheriting the AD code somehow but I can't see where. Also, it looks like you are running multiple apps in the same module - nothing wrong with that, except again its hard to see what is going on when I don't have access to any of the code that actually includes AD calls.

This line in your code:

```
 if self.properties.get('presence_required') else None)
```
Seems to be causing the issue yet it has nothing to do with AD that I can see - how does this generate a call to `run_at_sunset()`?

**Comment by bachya** [comment] 2018-11-03 22:10
>It's not at all clear from your code what the heck is going on here ;) I guess you are inheriting the AD code somehow but I can't see where. Also, it looks like you are running multiple apps in the same module - nothing wrong with that, except again its hard to see what is going on when I don't have access to any of the code that actually includes AD calls.

Here's the inheritance chain:

* [`ToggleAtTime`](https://github.com/bachya/smart-home/blob/777f3e117aa7844ca3392b6c0b4d0ac8ea17641a/appdaemon/settings/apps/switches.py#L172) inherits from [`BaseSwitch`](https://github.com/bachya/smart-home/blob/777f3e117aa7844ca3392b6c0b4d0ac8ea17641a/appdaemon/settings/apps/switches.py#L18).
* `BaseSwitch` inherits from [`Automation`](https://github.com/bachya/smart-home/blob/777f3e117aa7844ca3392b6c0b4d0ac8ea17641a/appdaemon/settings/apps/automation.py#L90).
* `Automation` inherits from [`Base`](https://github.com/bachya/smart-home/blob/777f3e117aa7844ca3392b6c0b4d0ac8ea17641a/appdaemon/settings/apps/automation.py#L15).
* `Base` inherits from `appdaemon.plugins.hass.hassapi.Hass`.

>This line in your code:
>> if self.properties.get('presence_required') else None)
>Seems to be causing the issue yet it has nothing to do with AD that I can see - how does this generate a call to run_at_sunset()?

All that does is handle a constraint. [These lines](https://github.com/bachya/smart-home/blob/777f3e117aa7844ca3392b6c0b4d0ac8ea17641a/appdaemon/settings/apps/switches.py#L179-L188) are where the `run_at_sunset()` (or comparable) gets set:

```python
if self.properties['schedule_time'] in ['sunrise', 'sunset']:
    method = getattr(
        self, 'run_at_{0}'.format(self.properties['schedule_time']))
    method(
        self.toggle_on_schedule,
        state=self.properties['state'],
        offset=self.properties.get('seasonal_offset', False),
        constrain_input_boolean=self.enabled_entity_id,
        constrain_anyone='just_arrived,home'
        if self.properties.get('presence_required') else None)
```

The first lines determine the value of a YAML key (looking for `sunrise` or `sunset`); if found, the `getattr()` call and the subsequent lines are what run `run_at_sunset()` in this case.

**Comment by acockburn** [comment] 2018-11-04 14:59
Is this consistent? Or does it happen some times and not others? Nothing significant changed in this area in 3.0.2 so it may be a race condition of some sort.

**Comment by bachya** [comment] 2018-11-04 15:06
Happens pretty consistently, but not every time. FYI, I encountered this on 3.0.0 and 3.0.1, as well.

**Comment by acockburn** [comment] 2018-11-04 19:39
Can you put together a simple app that reproduces this please? As far as I can see, this boils down to a call to `run_at_sunset()` in the `initialize()` call of an App - something that I and many others are doing without any issue, so lets eliminate the possibility of it being something in your code.

I double checked the initialization sequence of AD and verified that the self.sun values get set up before any apps are even instantiated, and definitely before their `initialize()` is called. The only other thing I can think of is that the setup is failing in some way - what timezone are you using?

**Comment by bachya** [comment] 2018-11-04 22:05
I just restarted my entire Docker stack (e.g., restarted both HASS and AD) and am seeing a new variant:

```
2018-11-04 14:59:20.592954 WARNING AppDaemon: ------------------------------------------------------------
2018-11-04 14:59:20.593116 WARNING AppDaemon: Unexpected error during state_update()
2018-11-04 14:59:20.593242 WARNING AppDaemon: ------------------------------------------------------------
2018-11-04 14:59:20.593858 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2346, in state_update
    self.process_state_change(namespace, data)
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2314, in process_state_change
    uuid_
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2248, in check_and_disapatch
    "kwargs": kwargs
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 536, in dispatch_worker
    constrained = self.check_constraint(arg, args["kwargs"][arg], self.objects[name]["object"])
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 495, in check_constraint
    unconstrained = method(value)
  File "/config/apps/automation.py", line 85, in constrain_sun
    or (position == 'down' and self.sun_down())):
  File "/usr/lib/python3.6/site-packages/appdaemon/appapi.py", line 288, in sun_down
    return self.AD.sun["next_rising"] < self.AD.sun["next_setting"]
KeyError: 'next_rising'
```

Once again, restarting AD after this initial launch causes the error to go away.

Notice that this time, `self.sun_down()` is the issue. So, I don't think it's specific to any of the individual method calls; something appears to be up with sun calculation in general.

>The only other thing I can think of is that the setup is failing in some way - what timezone are you using?

`America/Denver (GMT -7)`

**Comment by ReneTode** [comment] 2018-11-05 15:12
> Once again, restarting AD after this initial launch causes the error to go away.

in that case you probably have a race issue. the sunset and sunrise are not known in HA when AD is starting up.
@acockburn are you sure that AD is completely on hold before AD can retrieve those values from HA?

i still see lots of those kind of cases come by, in most cases when people have devicesettings or operatingsystemsettings that are not correctly set.

**Comment by acockburn** [comment] 2018-11-05 15:32
@ReneTode That used to be an issue in older versions of AD but AD hasn't been reliant on HASS for sunrise and sunset stuff for a while. The strange thing about this is that from the code, AD figures out sunrise and sunset times before any App is even instantiated, and long before their initialize() is called, so I don't see how this can actually happen unless there is an error somewhere in the log in setting up sunrise and sunset.

@bachya - I'm not trying to blame your code specifically - the way forward here is to simplify and find the minimum of what will cause this. When you have a simple app that sees the issue I'll take a shot at reproducing this locally then I have a chance to fix it.

**Comment by bachya** [comment] 2018-11-05 16:21
I have a simple reproduction, but I don't think it offers anything additional:

`test.yaml`:
```yaml
test:
  module: test
  class: Test
```

`test.py`:
```python
from appdaemon.plugins.hass.hassapi import Hass  # type: ignore


class Test(Hass):
  """Define a test app."""

    def initialize(self):
       """Initializate.""""
        self.run_at_sunset(self.test)

    def test(self, kwargs: dict) -> None:
        """Log at sunset."""
        self.log('HERE')
```

Log:
```
2018-11-05 09:17:07.883690 INFO AppDaemon: Initializing app test using class Test from module test
2018-11-05 09:17:07.883988 WARNING AppDaemon: ------------------------------------------------------------
2018-11-05 09:17:07.884139 WARNING AppDaemon: Unexpected error running initialize() for test
2018-11-05 09:17:07.884270 WARNING AppDaemon: ------------------------------------------------------------
2018-11-05 09:17:07.886112 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1581, in init_object
    init()
  File "/config/apps/hass.py", line 21, in initialize
    self.run_at_sunset(self.test)
  File "/usr/lib/python3.6/site-packages/appdaemon/appapi.py", line 434, in run_at_sunset
    handle = self._schedule_sun(name, "next_setting", callback, **kwargs)
  File "/usr/lib/python3.6/site-packages/appdaemon/appapi.py", line 420, in _schedule_sun
    event = self.calc_sun(type_)
  File "/usr/lib/python3.6/site-packages/appdaemon/appapi.py", line 261, in calc_sun
    return self.AD.calc_sun(type_)
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 897, in calc_sun
    return self.sun[type_].timestamp()
KeyError: 'next_setting'
```

@ReneTode's comment about OS settings is interesting. For reference, I'm running AD in an Alpine-based Docker container that has the correct date/time/timezone info set:

```
bash-4.3# date
Mon Nov  5 09:21:34 MST 2018
```

**Comment by acockburn** [comment] 2018-11-05 16:37
OK, thanks that's helpful. I'll see if I can reproduce this.

**Comment by ReneTode** [comment] 2018-11-06 00:48
@bachya i am now sure its absolutely the sme problem i encountered with quite a lot of other users.
the time settings inside the device, OS or docker are not as they supposed to be resulting in that AD  (and probably also HA) doesnt retrieve the wanted timesettings.

i think you set them as needed in the docker, and you probably set them in HA also.
so please find the time settings from your device and from your operating system. and make sure they are set the same.

**Comment by bachya** [comment] 2018-11-09 20:09
Here's what I have:

**Host:**

```bash
$ date
Fri Nov  9 13:07:11 MST 2018
```

**Home Assistant Docker Container:**

```bash
$ docker exec -it hass /bin/bash
root@hub:/usr/src/app# date
Fri Nov  9 13:08:00 MST 2018
```

**AppDaemon Docker Container:**

```bash
$ docker exec -it appdaemon /bin/bash
bash-4.3# date
Fri Nov  9 13:08:56 MST 2018
```

Everything appears normal and aligned. What am I missing?

**Comment by ReneTode** [comment] 2018-11-10 02:05
i didnt take a look at your code.

but you use the callbacks not how they are expected.

```
    def test(self, kwargs: dict) -> None:
        """Log at sunset."""
        self.log('HERE')
```
change that to:
```
    def test(self, kwargs):
        """Log at sunset."""
        self.log('HERE')
```
and you dont inherit you class the right way. (which is most probably causing trouble)

```
import appdaemon.plugins.hass.hassapi as hass
class test(hass.Hass):
```

**Comment by bachya** [comment] 2018-11-10 03:48
@ReneTode Regarding your first point, [type annotations are part of the Python 3 spec](https://docs.python.org/3/library/typing.html) and don't in any way affect the "correctness" of a method definition. If AppDaemon is having issues with them, there's a bigger problem. 😉

Your second point isn't correct. This:

```
from appdaemon.plugins.hass.hassapi import Hass
class test(Hass):
```

...is functionally equivalent to this:

```
import appdaemon.plugins.hass.hassapi as hass
class test(hass.Hass):
```

If there was an import error, Python would raise a `ModuleNotFoundError` exception.

**Comment by ReneTode** [comment] 2018-11-10 12:16
i maybe wrong, but you import the same thing but you connect to hass and not to hass.Hass which is a subpart.
so i am absolutely no python expert but i dont see that as the same.
you import the right thing but connect to the wrong part from what you import.

and about using things different then in the docs written (even if it is part of type annotations) i would always try to follow the docs when i run into a problem. only that way you can find out if there is a problem with the program.

remember you got a problem, with something that tons of people use without a problem, so there is something in your setup that isnt as expected.
the only thing we can do is try to find out what you do different then all those other people.

**Comment by bachya** [comment] 2018-11-10 16:28
I appreciate your input, but respectfully, it is incorrect. Let me help explain.

`appdaemon.plugins.hass.hassapi` is the full path to the `hassapi` module within the `hass` package. `Hass` is a class within the `hassapi` module. "Parts" and "sub-parts" are not nomenclature used in Python.

There are multiple ways to import and use that class. This:

```python
from appdaemon.plugins.hass.hassapi import Hass
class test(Hass):
```

...says, "Inherit from the `Hass` class, which can be found in the `hassapi` module of the `hass` package (which, itself, exists in the `plugins` package, etc.)

Compare that to your suggestion:

```python
import appdaemon.plugins.hass.hassapi as hass
class test(hass.Hass):
```

...which says, "Inherit from the `Hass` class, which can be found in the `hass` module (which has been defined as an alias of the `hassapi` module).”

They do the exact same thing. One isn't right and one isn't wrong. They are merely stylistic differences.

Regarding type annotations, I encourage you to read the documentation I posted. These annotations merely exist so that tools like `mypy` can discover possible issues before runtime. Their presence in no way alters or affects actual runtime behavior.

To help demonstrate that these items are not causing the issue, I recreated an app with your suggestions:

```python
import appdaemon.plugins.hass.hassapi as hass


class Test(hass.Hass):
  """Define a test app."""

    def initialize(self):
       """Initializate.""""
        self.run_at_sunset(self.test)

    def test(self, kwargs):
        """Log at sunset."""
        self.log('HERE')
```

The exact same issue arises on first run of AppDaemon:

```bash
2018-11-10 09:00:23.477462 INFO AppDaemon: Initializing app test using class Test from module test
2018-11-10 09:00:23.47803 WARNING AppDaemon: ------------------------------------------------------------
2018-11-10 09:00:23.477838 WARNING AppDaemon: Unexpected error running initialize() for test
2018-11-10 09:00:23.477861 WARNING AppDaemon: ------------------------------------------------------------
2018-11-10 09:00:23.477996 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1581, in init_object
    init()
  File "/config/apps/hass.py", line 21, in initialize
    self.run_at_sunset(self.test)
  File "/usr/lib/python3.6/site-packages/appdaemon/appapi.py", line 434, in run_at_sunset
    handle = self._schedule_sun(name, "next_setting", callback, **kwargs)
  File "/usr/lib/python3.6/site-packages/appdaemon/appapi.py", line 420, in _schedule_sun
    event = self.calc_sun(type_)
  File "/usr/lib/python3.6/site-packages/appdaemon/appapi.py", line 261, in calc_sun
    return self.AD.calc_sun(type_)
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 897, in calc_sun
    return self.sun[type_].timestamp()
KeyError: 'next_setting'
```

Once again, a restart of AppDaemon causes the error to disappear.

I hope this was helpful and instructive. I do think your prior point about environment issues is likely the culprit; I just don't see where the difference lies at the moment.

**Comment by ReneTode** [comment] 2018-11-10 16:50
its for sure very helpfull and thx for the clarification.

like i said i am no expert on python and there is a hugh amount of python that i dont know.
but i do know a hugh amount of the way appdaemon does if it is used the way its in the docs.

there are a lot of people that want to have help with debugging and the only debugging i know is the "appdaemon way"
your code is way of from what was intended for appdaemon. thats no problem because appdaemon is extremely flexible. the problem rises when it comes to errors. with the code you have its very hard to find if there is something in there that influences appdaemons normal working.

the error only rises when you create the app, but not after restarting. so it can be that something in your code has changed something.

what i want you to ask is to create a new appdir with just the test app and set that appdir in appdeamon.yaml, or remove everything you have in apps.yaml for a moment.

that way you have a clean appdaemon environment (without code from you to influence it)
then you can try to change something in the test app, save it and see if the error appears again.

if not, then we know its something in your code, if so then we know its something in the settings from device, os or HA or appdaemon.yaml (the last one is rarely the case)

**Comment by lociii** [comment] 2018-11-11 16:45
I'm encountering the same issue using the official docker acockburn/appdaemon:3.0.2

```
appdaemon        | 2018-11-11 17:33:10.166093 WARNING AppDaemon: ------------------------------------------------------------
appdaemon        | 2018-11-11 17:33:10.166199 WARNING AppDaemon: Unexpected error running initialize() for state_darkness_cover_shutdown
appdaemon        | 2018-11-11 17:33:10.166277 WARNING AppDaemon: ------------------------------------------------------------
appdaemon        | 2018-11-11 17:33:10.166718 WARNING AppDaemon: Traceback (most recent call last):
appdaemon        |   File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1581, in init_object
appdaemon        |     init()
appdaemon        |   File "/conf/apps/StateDarkness/StateDarknessCoverShutdown.py", line 18, in initialize
appdaemon        |     self.run_at_sunrise(self.deactivate)
appdaemon        |   File "/usr/local/lib/python3.6/site-packages/appdaemon/appapi.py", line 442, in run_at_sunrise
appdaemon        |     handle = self._schedule_sun(name, "next_rising", callback, **kwargs)
appdaemon        |   File "/usr/local/lib/python3.6/site-packages/appdaemon/appapi.py", line 420, in _schedule_sun
appdaemon        |     event = self.calc_sun(type_)
appdaemon        |   File "/usr/local/lib/python3.6/site-packages/appdaemon/appapi.py", line 261, in calc_sun
appdaemon        |     return self.AD.calc_sun(type_)
appdaemon        |   File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 897, in calc_sun
appdaemon        |     return self.sun[type_].timestamp()
appdaemon        | KeyError: 'next_rising'
```

**Comment by lociii** [comment] 2018-11-11 17:04
Additional info:
This only happens if appdaemon and home assistant containers are stopped and started together.
It doesn't happen If I start home assistant alone, wait a few minutes and start appdaemon later on.

**Comment by bachya** [comment] 2018-11-11 19:17
I attempted a completely cleaned out AppDaemon config with a single app; same behavior occurs. My details are the same as @lociii's: when both containers are restarted at the same time, this error occurs; starting HASS first, waiting a minute or two, then starting AppDaemon resolves it.

**Comment by acockburn** [comment] 2018-11-11 20:01
OK, great that helps to narrow it down. Can you give me the whole AppDaemon log please, right from the initial message.

**Comment by ReneTode** [comment] 2018-11-11 21:40
still that race thing.
andrew i think you need to create some kind of loop if AD is depending on a plugins setting, to wait for that setting to be correct. and in the HA case i would add a bit or check for all 4 values to be alive.

i know there have been several ways you have been working on this trouble and there have been fixes for it, but somehow it seems to come back every time.

i dont know how its checked at the moment but i think it should be something like:
```
def load_settings():
  if setting is inherited from plugin:
    while not setting_retrieved:
      if time_gone_by = 5 secs:
        log("still waiting to get setting {} from {}".format(setting,plugin))
      try:
        get_setting_from_plugin()
        setting_retrieved = True
      except:
        setting_retrieved = False
```

**Comment by bachya** [comment] 2018-11-12 01:09
@acockburn Here's my full log:

```
2018-11-11 16:00:01,394 CRIT Supervisor running as root (no user in config file)
2018-11-11 16:00:01,398 INFO supervisord started with pid 7
2018-11-11 16:00:02,400 INFO spawned: 'appdaemon' with pid 10
2018-11-11 16:00:02.960406 INFO AppDaemon Version 3.0.2 starting
2018-11-11 16:00:02.960653 INFO Configuration read from: /config/appdaemon.yaml
2018-11-11 16:00:02.961670 INFO AppDaemon: Starting Apps
2018-11-11 16:00:02.963753 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2018-11-11 16:00:03.025958 INFO AppDaemon: HASS: HASS Plugin Initializing
2018-11-11 16:00:03.026303 INFO AppDaemon: HASS: HASS Plugin initialization complete
2018-11-11 16:00:03.031381 INFO Dashboards are disabled
2018-11-11 16:00:03.031492 INFO Starting API
2018-11-11 16:10:33.780519 INFO AppDaemon: HASS: Connected to Home Assistant 0.82.0
2018-11-11 16:10:48.874226 INFO AppDaemon: Reading config
2018-11-11 16:10:49.084708 INFO AppDaemon: /config/apps/default.yaml added or modified
2018-11-11 16:10:49.088645 INFO AppDaemon: App 'test' added
2018-11-11 16:10:49.094978 INFO AppDaemon: Adding /config/apps to module import path
2018-11-11 16:10:49.122313 INFO AppDaemon: Initializing app test using class Test from module test
2018-11-11 16:10:49.208928 WARNING AppDaemon: ------------------------------------------------------------
2018-11-11 16:10:49.209014 WARNING AppDaemon: Unexpected error running initialize() for test
2018-11-11 16:10:49.209092 WARNING AppDaemon: ------------------------------------------------------------
2018-11-11 16:10:49.210946 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1581, in init_object
    init()
  File "/config/apps/hass.py", line 21, in initialize
    self.run_at_sunset(self.test)
  File "/usr/lib/python3.6/site-packages/appdaemon/appapi.py", line 434, in run_at_sunset
    handle = self._schedule_sun(name, "next_setting", callback, **kwargs)
  File "/usr/lib/python3.6/site-packages/appdaemon/appapi.py", line 420, in _schedule_sun
    event = self.calc_sun(type_)
  File "/usr/lib/python3.6/site-packages/appdaemon/appapi.py", line 261, in calc_sun
    return self.AD.calc_sun(type_)
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 897, in calc_sun
    return self.sun[type_].timestamp()
KeyError: 'next_setting'
```

**Comment by acockburn** [comment] 2018-11-12 16:08
@ReneTode  - there is a check like that in the code already - obviously it's not working but it is there!

Let me take a look at the log above and see if I can figure this out.

**Comment by acockburn** [comment] 2018-11-12 16:22
OK, I think I identified a race condition in the ASS plugin, the fix is pushed to dev - any chance you could test it? If not, it will be in 3.1.0.

**Comment by bachya** [comment] 2018-11-12 18:14
@acockburn I'd be happy to give it a test. Will report back.

**Comment by bachya** [comment] 2018-11-12 19:08
I patched `hassplugin.py` from https://github.com/home-assistant/appdaemon/commit/f73b04bfc892f4e8fa35d61fd409e752d18b058d in and restarted both HASS and AppDaemon containers at the same time. Same error. Is there something else that's needed?

**Comment by acockburn** [comment] 2018-11-12 19:16
Hmm. OK, can you set the DEBUG flag and give me a full log up until the error. If that doesn't help I'll maybe look at adding some diagnostics.

**Comment by bachya** [comment] 2018-11-12 20:58
When I attempt to use the latest `dev` Docker container, I get this upon startup:

```
2018-11-12 13:57:29.846522 INFO AppDaemon Version 3.1.0 starting
2018-11-12 13:57:29.846733 INFO Configuration read from: /conf/appdaemon.yaml
2018-11-12 13:57:29.848095 INFO AppDaemon: Starting Apps with 10 workers and 10 pins
2018-11-12 13:57:29.855423 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2018-11-12 13:57:29.908971 INFO AppDaemon: HASS: HASS Plugin Initializing
2018-11-12 13:57:29.910390 INFO AppDaemon: HASS: HASS Plugin initialization complete
2018-11-12 13:57:29.910678 INFO Starting Dashboards
2018-11-12 13:57:29.910877 WARNING ------------------------------------------------------------
2018-11-12 13:57:29.911015 WARNING Unexpected error during run()
2018-11-12 13:57:29.911120 WARNING ------------------------------------------------------------
2018-11-12 13:57:29.911884 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/appdaemon/admain.py", line 82, in run
    self.rundash = rundash.RunDash(self.AD, loop, self.logger, self.access, **hadashboard)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/rundash.py", line 130, in __init__
    dash_net = url.netloc.split(":")
TypeError: a bytes-like object is required, not 'str'
```

**Comment by acockburn** [comment] 2018-11-13 13:31
Hmm. What do you have for you appdaemon.yaml file? Dev works OK for me.

**Comment by acockburn** [comment] 2018-11-13 14:30
I've added some extra locking that might help here - it's in the latest dev when we fix the problem above.

**Comment by bachya** [comment] 2018-11-13 18:02
With the latest `dev` Docker image, I'm still getting this:

```
2018-11-13 10:58:34.017340 INFO AppDaemon Version 3.1.0 starting
2018-11-13 10:58:34.017489 INFO Configuration read from: /conf/appdaemon.yaml
2018-11-13 10:58:34.018517 INFO AppDaemon: Starting Apps with 10 workers and 10 pins
2018-11-13 10:58:34.020854 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2018-11-13 10:58:34.059355 INFO AppDaemon: HASS: HASS Plugin Initializing
2018-11-13 10:58:34.059631 INFO AppDaemon: HASS: HASS Plugin initialization complete
2018-11-13 10:58:34.059845 INFO Starting Dashboards
2018-11-13 10:58:34.060017 WARNING ------------------------------------------------------------
2018-11-13 10:58:34.060115 WARNING Unexpected error during run()
2018-11-13 10:58:34.060187 WARNING ------------------------------------------------------------
2018-11-13 10:58:34.060748 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/appdaemon/admain.py", line 82, in run
    self.rundash = rundash.RunDash(self.AD, loop, self.logger, self.access, **hadashboard)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/rundash.py", line 130, in __init__
    dash_net = url.netloc.split(":")
TypeError: a bytes-like object is required, not 'str'

2018-11-13 10:58:34.060828 WARNING ------------------------------------------------------------
2018-11-13 10:58:34.060940 INFO AppDeamon Exited
```

Here's my `appdaemon.yaml`:
```yaml
---
appdaemon:
  api_key: !secret api_key
  api_port: 5051
  threads: 10
  missing_app_warnings: false
  production_mode: true
  plugins:
    HASS:
      type: hass
      ha_url: http://hub.phil.lan:8123
      token: !secret ha_token
      app_init_delay: 15
```

Inside `apps`, I have one module defined in `test.yaml`:

```yaml
test:
  module: test
  class: Test
```

...which corresponds to `test.py`:

```python
from appdaemon.plugins.hass.hassapi import Hass  # type: ignore


class Test(Hass):
  """Define a test app."""

    def initialize(self):
       """Initializate.""""
        self.run_at_sunset(self.test)

    def test(self, kwargs: dict) -> None:
        """Log at sunset."""
        self.log('HERE')
```

I don't use HADashboard (which is where the error seems to come from).

**Comment by acockburn** [comment] 2018-11-14 22:41
This seems to be related to timing issues in the way HASS makes some of its data available - as a workaround, can you try setting `latitude`, `longitude`, `elevation` and `timezone` in your appdaemon.yaml and let me know if that helps?

**Comment by bachya** [comment] 2018-11-14 23:45
Unfortunately, adding those values to `appdaemon.yaml` on 3.0.2 doesn't help – same error.

I took your advice above and the latest `dev` seems to fix the issue; hasn't shown up in 10 or so straight down-and-ups of the Docker stack. So, maybe good? 😆 @lociii Have you confirmed?

**Comment by acockburn** [comment] 2018-11-15 17:45
I have tightened up this area of code further in the dev version. It annoys me that I haven't found the exact cause but it looks like things are improved :) I'll give it another 24 hours then close it if no one can reproduce this in the current dev.

**Comment by acockburn** [comment] 2018-11-16 20:36
OK, closing - please feel free to re-open if you see this error in 3.1.0 or later.

**Closed by acockburn** 2018-11-16 20:36 UTC
Labels: bug, question

**Comment by lociii** [comment] 2019-05-27 21:29
@acockburn is 3.1.0 a typo or a still unreleased version?
I'm running 3.0.5 and this still happens to me. To be more precise, it happens when starting appdaemon and homeassistant docker containers at the same time. I guess some part of HA is not yet ready which AD relies on.

**Comment by ReneTode** [comment] 2019-05-28 21:19
3.1.0 is a typo
3.0.5 is the latest release.

and you are right that HA is not ready in some cases when AD starts. the solution for that is to delay the startup from AD.

**Comment by lociii** [comment] 2019-05-28 21:52
That would be a workaround, not a solution. A solution would be to handle that case in AD and retry in intervals.
One should never assume that an external dependency is ready.

**Comment by ReneTode** [comment] 2019-05-29 16:14
in AD 4.0 there is a solution.
AD wont depend on the HA time settings anymore.

i forgot you could also get around that by adding the timezone, elevation, langtitude and longtitude to the appdaemon.yaml as described in the docs.

checking if the external dependency is ready is up to the users. there are to many things that can be lagging in a program like HA.
we dont want to start checking if all 1000 components in HA are ready. for sure not, because the user wont have them all.

HA gives a signal that its ready before all components are up and running. that a HA problem, not an AD problem.

**Comment by acockburn** [comment] 2019-05-29 17:26
Just to clarify a little - 3.1.0 is the version I put some more code in to help with this problem, however we made the decision to skip 3.1 and go to 4.0. 4.0 is not yet released, but it is where those changes will be (currently in the dev version).

**Comment by lociii** [comment] 2019-06-29 13:58
> in AD 4.0 there is a solution.
> AD wont depend on the HA time settings anymore.
> 
> i forgot you could also get around that by adding the timezone, elevation, langtitude and longtitude to the appdaemon.yaml as described in the docs.
> 
> checking if the external dependency is ready is up to the users. there are to many things that can be lagging in a program like HA.
> we dont want to start checking if all 1000 components in HA are ready. for sure not, because the user wont have them all.
> 
> HA gives a signal that its ready before all components are up and running. that a HA problem, not an AD problem.

Even if this ticket is closed and the underlying issue will be fixed in 4.0 I just wanted to mention that adding all these vars to the config doesn't make a difference for me. Just in case anyone else is searching for a workaround - the proposed one isn't guaranteed to work :)

**Comment by ReneTode** [comment] 2019-06-30 20:58
when you still have time errors, when the settings are set in appdaemon.yaml you probably have another problem.
for example when you have hass.io the settings will be overwritten when you dont set some other settings in the addon. or you might have set the settings the wrong way or on the wrong place.

when the right timesettings are set in appdaemon.yaml and the addon doesnt overwrite them, then the timesettings are set by appdaemon (and not inherited from HA) before any app is started.

feel free to come to our discordchat if you need help to resolve the problem.

**Comment by electrofloat** [comment] 2019-09-29 17:11
I have this exact same issue.
@ReneTode is there a timeframe for the 4.0 release?

Also the proposed workaround (adding timezone, elevation, longitude, latitude to appdaemon.yaml) - as others have mentioned - does not work.

**Comment by dlashua** [comment] 2019-10-01 12:16
@electrofloat if you're using docker for both homeassistant and appdaemon, I suggest you make your appdaemon container dependent on your homeassistant container if you are running AD v3. This can be done fairly easily with docker-compose.

There is no strict release schedule for AppDaemon. However, 4.0 is in beta now and users are reporting it to be quite stable. We'd love to see you on the beta, as well as more testers will allow us to ensure the 4.0 release is as smooth as possible.

In AD v4, AppDaemon waits for Home Assistant to be "ready" when the Home Assistant plugin is being used. And more features have been added to delay that even further (for instance, if desired, you can wait for zwave to be ready in Home Assistant).

If you would prefer to stay on AD v3 for the time being and are unable to handle this with docker-compose, I think an app could be written, that, when configured with a priority of 1, it's sole purpose would be to delay all other AppDaemon apps until Home Assistant was in a ready state. It's been a while since I've used AD v3, but, I think it should be possible. I'd be happy to try to work something up if it's needed.

**Comment by electrofloat** [comment] 2019-10-01 12:28
@dlashua Nope, no docker. Installed from pip and using systemd's 'after' to start it after homeassistant. But since it takes time to really start HA, that is not a solution for this.

Although if you are saying that 4.0 is stable enough now I can give it a try. But there are 3 branches: master, dev and 4.0.0b1. Which one is recommended for 4.0?

Also are there any new docs on the changes? (Like what you've mentioned new wait for zwave to be ready, etc.)

**Comment by dlashua** [comment] 2019-10-01 12:58
"master" is AD v3.0.5

"dev" is AD v4 with features that are still being tested for the next beta release. It's what I run, in production. It should be considered "alpha" quality. Generally speaking, it's pretty stable as once something hits "dev", if there are any issues we fix them pretty quickly. However, if you happen to update before the fix is merged, you may have issues (and, as always, we'd love it if you created an issue when you see anything, or, even better, a PR, if you're able).

"4.0.0b1" is the current beta, as released on Aug 30th. It appears to be quite stable. It, however, lacks features we've built for beta2 (which are in "dev") like the ability to run async methods in an app, sequences (AD's version of something like a Home Assistant "script"), authenticated and filterable stream, and much, much more.

If you're just looking to deal with the issue of AD starting up before HASS, "4.0.0b1" should suit you just fine. If you'd like to play with some of the new features before they are put in a beta, then go for "dev".

The documentation for the current "dev" version is available here: https://appdaemon.readthedocs.io/en/dev/DEV.html

We don't have documentation specifically for the beta, however, you can use the "dev" documentation as long as you are aware that some of the features documented there are not in "v4.0.0b1".

The configuration to delay AppDaemon apps until Home Assistant is ready are documented here:
https://appdaemon.readthedocs.io/en/dev/CONFIGURE.html#configuration-of-the-hass-plugin
and
https://appdaemon.readthedocs.io/en/dev/CONFIGURE.html#hass-plugin-startup-conditions

**Comment by electrofloat** [comment] 2019-10-01 13:05
Nice, Thank you for the detailed explanation and links.
Will try the "4.0.0b1" to see if my current issue resolves, and if it is, will see if I have time to read through changes and try the "dev" branch.

Thank you again!

**Comment by ReneTode** [comment] 2019-10-01 15:48
changes are logged here
https://appdaemon.readthedocs.io/en/dev/HISTORY.html

**Comment by electrofloat** [comment] 2019-10-01 18:24
@dlashua I can report that the 4.0.0b1 does indeed solve this issue. Will check the dev branch later when I'll have more free time.

(I had some issues installing this version, but nothing I couldn't resolve by myself.
If you want to take a look at it I pasted it on pastebin: https://pastebin.com/PkFExkCb )

**Comment by dlashua** [comment] 2019-10-02 13:27
Thanks for that. I'll look at getting setup.py fixed for the dateutil issue.

And I'm glad it's working for you well. AD4 has a LOT of improvements.
