### ISSUE TITLE
get_state creates an error in errorlog when the entity doesnt exist

### ISSUE THREAD

**Issue by ReneTode** [home-assistant/appdaemon#313] opened 2018-05-22 22:35 UTC
2018-05-22 23:05:25.199796 WARNING AppDaemon: ------------------------------------------------------------
2018-05-22 23:05:25.201123 WARNING AppDaemon: Unexpected error in worker for App test:
2018-05-22 23:05:25.201898 WARNING AppDaemon: Worker Ags: {'name': 'test', 'id': UUID('27fabfd4-ff6e-4da3-976e-e66cb79b9a96'), 'type': 'attr', 'function': <bound method test.test of <test.test object at 0x7fd3240feac8>>, 'attribute': 'state', 'entity': 'persistent_notification.httplogin', 'new_state': None, 'old_state': 'notifying', 'kwargs': {'handle': UUID('e76976b8-9824-4d1b-ba62-2d7d05d1ebad')}}
2018-05-22 23:05:25.202756 WARNING AppDaemon: ------------------------------------------------------------
2018-05-22 23:05:25.206046 WARNING AppDaemon: Traceback (most recent call last):
  File "/mnt/usbdrive/pi/ADvenv/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 601, in worker
    self.sanitize_state_kwargs(app, args["kwargs"]))
  File "/mnt/usbdrive/pi/appdaemon/appdaemon/conf/apps/testapps/test.py", line 31, in test
    test = self.get_state("persistent_notification.httplogin",attribute="message")
  File "/mnt/usbdrive/pi/ADvenv/lib/python3.6/site-packages/appdaemon/plugins/hass/hassapi.py", line 96, in get_state
    return super(Hass, self).get_state(namespace, entity, **kwargs)
  File "/mnt/usbdrive/pi/ADvenv/lib/python3.6/site-packages/appdaemon/appapi.py", line 214, in get_state
    return self.AD.get_state(namespace, device, entity, attribute)
  File "/mnt/usbdrive/pi/ADvenv/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 730, in get_state
    if attribute in self.state[namespace][entity_id]["attributes"]:
TypeError: 'NoneType' object is not subscriptable

2018-05-22 23:05:25.206633 WARNING AppDaemon: ------------------------------------------------------------

**Comment by acockburn** [comment] 2018-05-23 12:39
Thanks Rene

**Comment by acockburn** [comment] 2018-05-24 11:59
I took a look at this and in my tests it works as expected - it returns `None` for a non-existent entity.

Can you supply the code for the app please? Also what version of AD are you running?

**Comment by ReneTode** [comment] 2018-05-24 13:44
i am running 3.0.1
this was the app
```
import appdaemon.plugins.hass.hassapi as hass

class test(hass.Hass):

    def initialize(self):
        self.listen_state(self.test,"persistent_notification.httplogin")

    def test(self, entity, attribute, old, new, kwargs):
        test = self.get_state("persistent_notification.httplogin",attribute="message")
        self.log(test)
```
the error appears when the persistant notification is closed.
so the first time the entity exists, but the second time the callback gets called the error appears.

i think it returns none for an none existing entity if you ask for the state from an entity, but in this case there is asked for an attribute from a non existing entity or a non existing attribute.

**Comment by Odianosen25** [comment] 2018-05-31 09:27
@acockburn,

As a follow up to this, I have also noticed that `self.get_state()` gives me an issue when using `self.set_app_state()` when I have different namespaces.

In my scenario, I have an app, that gets data in a namespace, and I want to use the `self.set_app_state()` to another app within a different namespace. Now this works fine if I am using it within the any namespace, to a hass namespace. But if I am to try and use it to send data to another namespace for example:

`self.set_app_state(entity_id, state = state, attributes=attribute, namespace = 'mqtt')`
I get a get error
```
  File "/srv/appdaemon/lib/python3.5/site-packages/appdaemon/plugins/hass/hassapi.py", line 155, in set_app_state
    if entity_id in self.get_state():
TypeError: argument of type 'NoneType' is not iterable
```
After looking via the `hassapi.py` file, I think the issue is here

```
def set_app_state(self, entity_id, **kwargs):
    namespace = self._get_namespace(**kwargs)
    if "namespace" in kwargs:
        del kwargs["namespace"]
    self._check_entity(namespace, entity_id)
    self.AD.log(
        "DEBUG",
        "set_app_state: {}, {}".format(entity_id, kwargs)
    )
     if entity_id in self.get_state():
       new_state = self.get_state()[entity_id]
    else:
       # Its a new state entry
       new_state = {}
       new_state["attributes"] = {}
 ```    
The line ` if entity_id in self.get_state():`, doesn't make use of the namespace in the `get` function and so the error.

Another option is if its a `None`, which it will be if the namespace being used has no entity in it, can it be done in such a way that it avoids the error? So if `self.get_state()` returns a `None` (which it will do), it is also seen as its not existing and just create it.

Thanks

**Comment by Odianosen25** [comment] 2018-05-31 09:33
@acockburn, @ReneTode,

As follow up to the above, can I get a confirmation on how creating entities really work? 

When I use `self.set_app_state()`, I assume I am "creating" an entity and I get the following in my log

`2018-05-31 08:24:44.247110 WARNING AppDaemon: settings: Entity mqtt.hallway_motion_sensor not found in AppDaemon`

Which totally makes sense.

But if I am to use the same entity after a while, it seems it "disappears" in AppD and it get this same log entry after a while:

```
2018-05-31 08:24:44.247110 WARNING AppDaemon: settings: Entity mqtt.hallway_motion_sensor not found in AppDaemon
2018-05-31 08:24:44.423531 INFO security_app: check_home_sensors, Entity: mqtt.hallway_motion_sensor, State: False, Attributes: {'timestamp': 1527751484.246945, 'illuminance': 0}
2018-05-31 08:25:57.179030 INFO security_app: check_home_sensors, Entity: mqtt.hallway_motion_sensor, State: False, Attributes: {'battery': '100.00', 'timestamp': 1527751556.926158, 'illuminance': 0, 'voltage': 3045}
2018-05-31 08:25:59.364449 INFO security_app: check_home_sensors, Entity: mqtt.hallway_motion_sensor, State: False, Attributes: {'battery': '100.00', 'voltage': 3045, 'illuminance': 0, 'timestamp': 1527751559.014346}
2018-05-31 08:28:44.837243 INFO security_app: check_home_sensors, Entity: mqtt.hallway_t-h-p_sesnor, State: None, Attributes: {'humidity': 69.04, 'pressure': 998, 'battery': '95.00', 'temperature': 23.71, 'voltage': 2975, 'timestamp': 1527751724.582097}
2018-05-31 08:33:24.594568 INFO security_app: check_home_sensors, Entity: mqtt.hallway_motion_sensor, State: True, Attributes: {'battery': '100.00', 'voltage': 3045, 'illuminance': 0, 'timestamp': 1527752004.195241}
2018-05-31 08:33:24.600297 INFO security_app: check_home_sensors, Entity: mqtt.hallway_motion_sensor, State: True, Attributes: {'battery': '100.00', 'voltage': 3045, 'illuminance': 0, 'timestamp': 1527752004.195241}
2018-05-31 08:34:24.156222 WARNING AppDaemon: settings: Entity mqtt.hallway_motion_sensor not found in AppDaemon
```
Not sure what this happens, as I was hoping I could use it to "store" the state of some mqtt events which I could access when I need. Example battery level of my zigbee devices.

Right now I use the `self.global_vars` to do that, but I really like avoiding using it. And If I could get this to work, it will be nice so I could normal `self.get_state('mqtt.hallway_motion_sensor', attribute = 'battery')` to get my battery state or monitor changes.

But as it seems to "disappear", I don't get what is going on.

Thanks and regards

**Comment by Odianosen25** [comment] 2018-06-01 06:17
And this is more errors, after I tried to change the `self.get_state()` function to

```
if self.get_state(namespace = namespace).get(entity_id, None) != None:
       new_state = self.get_state(namespace = namespace)[entity_id]
else:
       # Its a new state entry
       new_state = {}
       new_state["attributes"] = {}
```

```
2018-05-31 19:30:25.138934 WARNING AppDaemon: ------------------------------------------------------------
2018-05-31 19:30:30.008468 WARNING AppDaemon: ------------------------------------------------------------
2018-05-31 19:30:30.010387 WARNING AppDaemon: Unexpected error in worker for App settings:
2018-05-31 19:30:30.012332 WARNING AppDaemon: Worker Ags: {'id': UUID('57f783b6-202f-4d76-9b6e-4ac1e13ddcca'), 'function': <bound method Settings.mqtt_entity of <settings.Settings object at 0x6ba23410>>, 'kwargs': {}, 'event': 'MQTT', 'data': {'topic': 'zigbee2mqtt/Living Room Window', 'payload': '{"battery":"100.00","voltage":3015}'}, 'name': 'settings', 'type': 'event'}
2018-05-31 19:30:30.014310 WARNING AppDaemon: ------------------------------------------------------------
2018-05-31 19:30:30.017559 WARNING AppDaemon: Traceback (most recent call last):
  File "/srv/appdaemon/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 595, in worker
    funcref(args["event"], data, args["kwargs"])
  File "/home/homeassistant/appdaemon/apps/settings/settings.py", line 54, in mqtt_entity
    self.set_app_state(entity_id, state = state, attributes = attribute)
  File "/srv/appdaemon/lib/python3.5/site-packages/appdaemon/plugins/mqtt/mqttapi.py", line 89, in set_app_state
    self._check_entity(namespace, entity_id)
  File "/srv/appdaemon/lib/python3.5/site-packages/appdaemon/appapi.py", line 66, in _check_entity
    if not self.AD.entity_exists(namespace, entity):
  File "/srv/appdaemon/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 618, in entity_exists
    if namespace in self.state and entity in self.state[namespace]:
TypeError: argument of type 'NoneType' is not iterable

2018-05-31 19:30:30.024240 WARNING AppDaemon: ------------------------------------------------------------
```

**Comment by ReneTode** [comment] 2018-06-01 10:16
```
  File "/srv/appdaemon/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 618, in entity_exists
    if namespace in self.state and entity in self.state[namespace]:
```
thats the part causing the error.
when namespace is none then self.state[namespace] thros the error
so the code needs to be changed to:

```
    if namespace in self.state: 
        if entity in self.state[namespace]:
```

**Comment by Odianosen25** [comment] 2018-06-01 10:30
Thanks @ReneTode,

But the namespace does exist, just that the entity doesn't exist in the namespace (as I am just trying to create it). Doesn't it now mean that this line `if entity in self.state[namespace]:` will still create the errors? Not home to test though.

I plan to try changing the `appdaemon.py` file this weekend, and try doing a pull request if it all works out.

Thanks and regards

**Comment by ReneTode** [comment] 2018-11-11 12:33
its a test app i did write for another user months ago. (and only used for testing back then)
im sure that if you took care of it, the problem is gone.

**Comment by Odianosen25** [comment] 2018-11-11 12:55
Yes I agree with @ReneTode, it had gone and you added a new one with the updated, but submitted a PR for that.

**Comment by acockburn** [comment] 2018-11-11 14:08
OK thanks both of you. Closing.

**Closed by acockburn** 2018-11-11 14:08 UTC
