### ISSUE TITLE
Appdaemon set_state() cancel friendly name from sensor created by user

### ISSUE THREAD

**Issue by MikeTheCleric** [home-assistant/appdaemon#904] opened 2020-03-02 16:46 UTC
Hi,

After the last update of Appdaemon 4 for Home Assistant (version 0.2.1) I noticed an unusual behaviour of the method "set_state". When I use it the entity targeted lost all the attributes instead of update only the state. I tried this on a new app and the result is: 

Appdaemon log:
```
2020-03-02 17:08:13.469011 INFO Prove: ### START TEST ###
2020-03-02 17:08:13.477904 INFO Prove: friendly name before: Flag gestione luci
2020-03-02 17:08:13.524170 INFO Prove: friendly name after: None
2020-03-02 17:08:13.528736 INFO Prove: ### STOP TEST ###
```
Code:
```
import appdaemon.plugins.hass.hassapi as hass

class PROVE(hass.Hass):

    def initialize(self):
        self.listen_state(self.test, entity = "input_boolean.avvio", new = "on")

    def test(self, entity, attribute, old, new, kwargs):
        self.log("### START TEST ###")

        fn = self.get_state("sensor.light_flag", attribute="friendly_name")
        self.log("friendly name before: " + str(fn))

        self.set_state("sensor.light_flag", state = 1)

        fn = self.get_state("sensor.light_flag", attribute="friendly_name")
        self.log("friendly name after: " + str(fn))

        self.log("### STOP TEST ###")
```
Sensor configuration:
```
sensor:
  light_flag:
  friendly_name: Flag gestione luci
  value_template: >
    0
```
Home Assistant version: 0.105.3
Supervisor version: 3.10
The documentation doesn't explain if this is a bug, so someone can explain how use set_state properly??

Thanks in advance.

**Comment by acockburn** [comment] 2020-03-02 16:48
Can you let us know the actual AppDaemon version please? From the startup log.

**Comment by MikeTheCleric** [comment] 2020-03-02 16:50
Here you are
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.2.3
 You are running the latest version of this add-on.
 System: HassOS 3.10  (armv7 / raspberrypi3)
 Home Assistant Core: 0.105.3
 Home Assistant Supervisor: 206
-----------------------------------------------------------
```

**Comment by Odianosen25** [comment] 2020-03-02 17:09
@MikeTheCleric,

The way HA works is that if you set only state from AD, as you noticed it cancels the rest. It’s not an AD issue, but the way HA handles the rest call for set state.

For this reason, when wanting to set a state in HA and keep the attributes. First copy all the attributes using get_state(entity_id, attribute=“all”). You get a dictionary, and modify the “state” value. Then use this new dictionary in the set_state function.

Hope this helps?

**Comment by MikeTheCleric** [comment] 2020-03-02 17:23
Thanks for the reply. I used this method with Appdaemon 3 and the attributes doesn't disappear. I noticed this behaviour only with the upgrade from 3 to 4. It worked as you say even with AD 3??

**Comment by Odianosen25** [comment] 2020-03-03 13:55
@MikeTheCleric,

Apologies just responding back. It’s should be the same for both, as the rest api hasn’t changed really. But I am certain what I have told you, is the way to get around this.

Regards

**Comment by Odianosen25** [comment] 2020-04-11 11:36
CLosing this @MikeTheCleric, if anything do reopen.

Thanks

**Closed by Odianosen25** 2020-04-11 11:36 UTC

**Comment by spasche** [comment] 2020-07-27 19:36
I can confirm that the behavior of `set_state()` changed between v3 and v4.

In v3, `set_state()` will do a `get_state()` first and merge existing attributes with the new ones: see https://github.com/AppDaemon/appdaemon/blob/3.0.5/appdaemon/plugins/hass/hassapi.py#L109

In v4, previous state and attributes are ignored, so existing attributes are wiped if not given.

I'm not sure if the new behavior is expected, I didn't see anything about that in the changelog and that's a rather important breaking change in my opinion.

This can have other unwanted side effects. For instance, calling `set_state` on `input_number` or `input_select` entities will clear existing attributes such as the range or list of possible states and the entities will look broken on the UI.

I'm using the following helper as a workaround:
```
    # see https://github.com/AppDaemon/appdaemon/issues/904
    async def update_state(self, entity, state=None, attributes=None):
        new_state = state if state is not None else await self.get_state(entity)

        new_attributes = (await self.get_state(entity, attribute="all"))["attributes"]
        if attributes is not None:
                new_attributes.update(attributes)

        await self.set_state(entity, state=new_state, attributes=new_attributes)
```

**Comment by ReneTode** [comment] 2020-07-27 20:33
i believe that was an intended change that hasnt been documented.
in AD 3 it wasnt possible to remove attributes that were created by AD.
the result was that you always needed to restart HA to get rid of obsolete attributes.

for those who dont use async it would simply be:

```
attributes = self.get_state(entity, attribute="all").get("attributes", {})
# add additional attributes
self.set_state(entity, state = state, attributes = attributes)
```

**Comment by spasche** [comment] 2020-07-28 19:02
Thanks for the clarification. I understand the use case for clearing existing attributes.

Now I'm not convinced the new `set_state()` behavior is the best user experience, since you have to take special measures when working with `input_select` or `input_number` entities for instance.

It would be nice if either `set_state()` had a flag to specify if existing attributes should be preserved or have something like `update_state()` built-in.

**Comment by ReneTode** [comment] 2020-07-29 00:08
set_state was originally never designed to set the state from input_selects or input_numbers
you got services for that.

in most cases its better to use the services that exist. only for cases where no service exist you can use set_state (which is actually just to manipulate the state from sensors that are created by AD.)

thats probably why most people have no problem with the extra line of code. because its not needed in most cases.

AD even got special functions for updating the state from things like input_select and input_number ( set_value, set_textvalue and select_option)

but off course call_service works also.

**Comment by spasche** [comment] 2020-07-29 08:30
That makes a lot of sense, I was doing it wrong on v3 and saw the consequences on v4 😉.

Thanks a lot for the detailed explanations!

**Comment by ReneTode** [comment] 2020-07-29 11:00
your welcome.
