### ISSUE TITLE
HAdasboard on iOS 9.3.5 (iPad mini 1st gen)

### ISSUE THREAD

**Issue by akloeckner** [home-assistant/appdaemon#735] opened 2019-09-26 10:03 UTC
I am looking for an interface to HA from my old iPad mini. In native lovelace, I ran into this issue: https://github.com/home-assistant/home-assistant-polymer/issues/3722. By now, there seems to be a fix, but anyways, the issue got me pointed to HAdashboard. On my Android phone, it works fine. However, on my iPad, not so well.

The iPad does not get status updates from the server. So, I have a widget for a light and one for a group (containing the light). If I switch on the light by tapping the widget, the icon changes. But not the icon of the group, which it should. Also, if I switch on the light through another device, nothing happens in HAdashboard on my iPad. Again: all of this works fine on my Android.

Are there also compatibility issues with older iOS, here? Or is the error in my side?

**Comment by ReneTode** [comment] 2019-09-26 11:20
there are compatibility issues with older Ipads.
but i have seen solutions come by and i know that andrew was working on that.
if it isnt already in AD 4 beta(which you probably dont have) then it will be there when the full release comes.

**Comment by acockburn** [comment] 2019-09-26 12:40
Yes, as Rene says, we should have a fix for this by the end of the beta. Closing as a duplicate of #469

**Closed by acockburn** 2019-09-26 12:40 UTC

**Comment by akloeckner** [comment] 2019-09-26 14:11
Great to know, you're at it. Thanks, folks!
