### ISSUE TITLE
listen_state with delay does not cleanup scheduled jobs on app restart

### ISSUE THREAD

**Issue by turboc1208** [home-assistant/appdaemon#507] opened 2019-01-31 18:09 UTC
This is what I think is happening.  I looked at the callbacks this morning and I had over a page of schedule callbacks for a job that only has listen_state calls with a delay.  As we know a listen_state with a delay (listen for when office light has been on for 10 minutes) creates a scheduled callback for 10 minutes later to do its work.  When I restart the app though, even though the listen_state callbacks appear to be cleaned up the associated schedule events seem to hang out there (or at least that's what the admin console seems to say), restarting the app itself doesn't help, but restarting appdaemon clears it up.

**Comment by acockburn** [comment] 2019-05-30 20:16
What happens when you reload th admin gui? I think this is a cosmetic issue in the admin page rather than an issue with the callbacks actually being retained

**Comment by acockburn** [comment] 2019-05-30 20:17
I think this is a dupe of #499 so closing.

**Closed by acockburn** 2019-05-30 20:17 UTC
Labels: bug
