### ISSUE TITLE
Dash_Password doesn't read from secrets.yaml

### ISSUE THREAD

**Issue by eugenelai** [home-assistant/appdaemon#415] opened 2018-11-07 05:23 UTC
Noticed that dash_password doesn't use the password stored in secrets.yaml file anymore, it just uses the dash_password variable. E.g.

```
hadashboard:
  dash_url: https://xxx.duckdns.org:5050
  dash_dir: /config/appdaemon/dashboards
  dash_ssl_certificate: /ssl/fullchain.pem
  dash_ssl_key: /ssl/privkey.pem
  dash_password: !secret dash_password
```
The password to login to HADashboard is "dash_password" and not what is stored in the secrets.yaml file under dash_password

**Comment by mkerner** [comment] 2018-11-09 14:04
This also seems to be the case with the dash_url.

**Comment by acockburn** [comment] 2018-11-10 19:10
This works perfectly for me - are you using hass.io by any chance?

**Comment by mkerner** [comment] 2018-11-12 14:15
I'm running hass.io on a docker setup

**Comment by acockburn** [comment] 2018-11-12 16:30
@frenck - Any possibility this is an issue with HASS.io? I can;t reproduce locally with a pip install.

**Comment by acockburn** [comment] 2018-11-13 14:15
The hass.io author @frenck is looking into this to see if it is a hass.io related issue.

**Comment by acockburn** [comment] 2018-11-16 20:36
Closing as this seems to be a hass.io issue.

**Closed by acockburn** 2018-11-16 20:36 UTC
Labels: question
