### ISSUE TITLE
crash after restarting HA

### ISSUE THREAD

**Issue by turboc1208** [home-assistant/appdaemon#123] opened 2017-08-21 23:17 UTC
a couple of times now, when restarting HA, I've noticed that AD was down.  No errors in the appdaemon.err file, nothing in the log file either.  I did capture the following from the syslog.  Not much but it's all I've got.
AD Version 2.1.7
HA Version 0.51.2

I believe it happened when HA shutdown because there are no "ha not available waiting 5 second" kind of messages in the log.

Aug 21 18:06:53 hass2 systemd[1]: appdaemon.service: main process exited, code=killed, status=11/SEGV
Aug 21 18:06:53 hass2 systemd[1]: Unit appdaemon.service entered failed state.

**Comment by acockburn** [comment] 2017-09-17 13:46
Closing - unable to reproduce

**Closed by acockburn** 2017-09-17 13:46 UTC
