### ISSUE TITLE
Config.get missing argument

### ISSUE THREAD

**Issue by SeaquestNet** [home-assistant/appdaemon#113] opened 2017-08-11 09:23 UTC
2017-08-11 10:21:23.762581 INFO AppDaemon Version 2.1.4 starting
2017-08-11 10:21:23.762693 INFO Configuration read from: /conf/appdaemon.cfg
Traceback (most recent call last):
File "/usr/local/bin/appdaemon", line 11, in <module>
load_entry_point('appdaemon==2.1.4', 'console_scripts', 'appdaemon')()
File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1749, in main
ha.log(conf.logger, "DEBUG", "AppDaemon Section: {}".format(config.get("AppDaemon")))
TypeError: get() missing 1 required positional argument: 'option'

Seems to be requiring an "option" argument!

**Comment by acockburn** [comment] 2017-08-11 11:46
This is a little strange - that issue was fixed in the version you are running, and the code that caused the problem is not even at that line anymore. 

Can you run `$ pip show appdaemon' for me please?

I released a new version just to be on the safe side - if you upgrade now the problem should be fixed. Let me know how it goes.

**Comment by acockburn** [comment] 2017-08-13 16:29
Should be fixed - no response so closing.

**Closed by acockburn** 2017-08-13 16:29 UTC
