### ISSUE TITLE
setup.py is broken due to __version__ being defined in the wrong place

### ISSUE THREAD

**Issue by basnijholt** [home-assistant/appdaemon#817] opened 2019-11-21 18:12 UTC
In `setup.py` the attribute `__version__` is imported from `appdaemon.utils`.

However, in `appdaemon.utils`, `dateutil` (a thrid party package) is imported.

So before the requirements are installed `dateutil` will be imported, which is not possible.

I would argue that `__version__` doesn't belong in `utils`. Rather create a file `version.py` and then load it in `setup.py` like:
```
# Loads version.py module without importing the whole package.
def get_version(package_name):
    import os
    from importlib.util import module_from_spec, spec_from_file_location

    spec = spec_from_file_location("version", os.path.join(package_name, "version.py"))
    module = module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.__version__
```

**Comment by acockburn** [comment] 2019-11-21 18:18
Duplicate of #780

**Closed by acockburn** 2019-11-21 18:18 UTC
