### ISSUE TITLE
mailformed apps.yaml turns AD into the infinite loop 

### ISSUE THREAD

**Issue by dummylabs** [home-assistant/appdaemon#862] opened 2020-01-25 16:02 UTC
Thank you for the great product! I've discovered recently that the following `apps.yaml` turns AD4 into the infinite loop:

```
test:
  module:module
  class:class
```

The same effect can be reproduced by omitting colons and/or the text after them. It's a bit of a challenge to figure out what's wrong when you missed spaces both for `module` and `class` params. Below is the recurring part of the AD startup log: 

```
2020-01-25 18:43:56.273364 WARNING AppDaemon: ------------------------------------------------------------
2020-01-25 18:43:56.273636 WARNING AppDaemon: Unexpected error during run()
2020-01-25 18:43:56.273833 WARNING AppDaemon: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/__main__.py", line 135, in run
    loop.run_until_complete(asyncio.gather(*pending))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/appdaemon/utility_loop.py", line 112, in loop
    await self.AD.app_management.check_app_updates(mode="init")
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 738, in check_app_updates
    for app in self.apps_per_module(self.get_module_from_path(module["name"])):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 953, in apps_per_module
    if app not in self.non_apps and self.app_config[app]["module"] == module:
TypeError: string indices must be integers
2020-01-25 18:43:56.275167 INFO AppDaemon: Previous message repeated 1 times
2020-01-25 18:43:56.275327 INFO AppDaemon: AppDaemon Exited
/usr/lib/python3.8/site-packages/appdaemon/__main__.py:134: DeprecationWarning: Task.all_tasks() is deprecated, use asyncio.all_tasks() instead
  pending = asyncio.Task.all_tasks()
/usr/lib/python3.8/site-packages/aiohttp/connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
/usr/lib/python3.8/site-packages/aiohttp/locks.py:21: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._event = asyncio.Event(loop=loop)
/usr/lib/python3.8/asyncio/events.py:81: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._context.run(self._callback, *self._args)
```

**Comment by ReneTode** [comment] 2020-01-25 16:38
AD is an infinite loop in itself.

was that the only app thay you had?
normally when AD discovers wrong yaml it will ignore it.

i guess AD sees this as correct yaml and module not presented for a created app.

i think we need to add a check for

module == None

and when that happens the app will be ignored.

**Comment by dummylabs** [comment] 2020-01-26 19:22
I have 20+ apps. 
Under the infinite loop, I meant that it continuously sends stack traces into the log file.

**Comment by ReneTode** [comment] 2020-01-26 22:56
ok, thx for the extra info.
i guess AD tries to create the app over and over, but it is missing the info it needs.

**Comment by dlashua** [comment] 2020-01-27 15:04
Are you, by chance, running this in Docker or using some other container type deployment? Or, do you have appdaemon in systemd/init.d?

**Comment by dummylabs** [comment] 2020-01-28 14:11
I have it installed as a Hass.io add-on, that is, in a Docker container: https://community.home-assistant.io/t/community-hass-io-add-on-appdaemon-4

**Comment by acockburn** [comment] 2020-01-30 13:54
This malformed YAML bypassed ,y existing check for module and class because for some reason, YAML converted that module entry to a string including the keywords "class and "module". I added a check to make sure it was a dict. Fix is in the next release.

**Closed by acockburn** 2020-01-30 13:54 UTC

**Comment by ReneTode** [comment] 2020-01-30 15:03
@acockburn the problem is that it is a dict.
there needs to be checked for
module != None
class != None

**Comment by acockburn** [comment] 2020-01-30 15:44
That check was already being done, the malformed YAML bypassed it - as I said, it now checks correctly for the case above.

**Comment by ReneTode** [comment] 2020-01-30 15:58
ah ok.
just making sure there were no miscommunications ;)
