### ISSUE TITLE
Error in main log when a mistake is made in App

### ISSUE THREAD

**Issue by Odianosen25** [home-assistant/appdaemon#488] opened 2019-01-20 17:40 UTC
I made a mistake in an app, and I got the following in main log file

```
2019-01-20 16:04:39.048432 WARNING AppDaemon: ------------------------------------------------------------
2019-01-20 16:04:39.050082 WARNING AppDaemon: Unexpected error during utility()
2019-01-20 16:04:39.052013 WARNING AppDaemon: ------------------------------------------------------------
2019-01-20 16:04:39.060004 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/app_management.py", line 644, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/utils.py", line 230, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/app_management.py", line 412, in read_app
    importlib.reload(self.modules[module_name])
  File "/usr/lib/python3.5/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 626, in _exec
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/.appdaemon/conf/apps/ha_group_app.py", line 84
    
    ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/utility_loop.py", line 121, in loop
    await self.AD.app_management.check_app_updates()
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/app_management.py", line 657, in check_app_updates
    if self.app_config[app]["module"] == module:
TypeError: string indices must be integers

2019-01-20 16:04:39.062078 WARNING AppDaemon: ------------------------------------------------------------
```
Though the error was shown in error file, it shouldn't have given me such a scary stuff in log file

:)

**Comment by acockburn** [comment] 2019-08-10 19:55
The problem is that there was an exception in the exception, not incorrect log placement, so logging this to the main log was correct behavior. However, I am not sure how the exception in the exception happened. Can you easily reproduce this?

**Comment by Odianosen25** [comment] 2019-08-10 20:14
Yes it is to easily produce, as when there is a syntax error in an apps, it is shown both in the error log and main log. So that's the headache.

Regards

**Comment by acockburn** [comment] 2019-09-04 19:47
This might be fixed in the latest dev - can you re-test please?

**Comment by acockburn** [comment] 2019-09-06 18:41
Closing pending re-test

**Closed by acockburn** 2019-09-06 18:41 UTC
Labels: bug
